version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    #network_mode: "host" 
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=10d
      - --storage.tsdb.wal-compression
      - --web.enable-lifecycle
      - --web.listen-address=0.0.0.0:9090
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-remote-write-receiver
      # - --web.external-url=/prometheus
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/prometheus/etc:/etc/prometheus
      - prometheus-data:/prometheus

  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ${PWD}/alertmanager/:/etc/alertmanager/
  #   restart: always
  #   command:
  #     - --config.file=/etc/alertmanager/alertmanager.yml
  #     - --storage.path=/alertmanager
  #   deploy:
  #     mode: global

  #  prometheus-pushgateway:
  #  image: prom/pushgateway
  #  container_name: pushgateway
  #  restart: always
  #  command:
  #    - '--web.listen-address=:9991'
  #    - '--push.disable-consistency-check'
  #    - '--persistence.interval=5m'
  #  ports:
  #    - 9991:9991

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
      # - GF_SERVER_PROTOCOL=http
      # - GF_SERVER_DOMAIN=jumpbox
      # - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      # - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/grafana:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  nginx:
    image: nginx
    container_name: nginx
    depends_on: 
      - grafana
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  prometheus-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind" 
      device: "/opt/monitoring/prometheus/data/"
  grafana-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind" 
      device: "/opt/monitoring/grafana/data/"

networks:
  default:
    name: confluent
