version: '3'
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    #network_mode: "host" 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=10d'
      - '--storage.tsdb.wal-compression'
      - '--web.enable-lifecycle'
      - '--web.listen-address=0.0.0.0:9090'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./prometheus/etc:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  #  prometheus-pushgateway:
  #  image: prom/pushgateway
  #  container_name: pushgateway
  #  restart: always
  #  command:
  #    - '--web.listen-address=:9991'
  #    - '--push.disable-consistency-check'
  #    - '--persistence.interval=5m'
  #  ports:
  #    - 9991:9991

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    depends_on: 
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    ports:
      - 3000:3000

  kafka-lag-exporter:
    image: lightbend/kafka-lag-exporter:0.6.8
    container_name: kafka-lag-exporter
    hostname: kafka-lag-exporter
    restart: always
    #command: ["/opt/docker/bin/kafka-lag-exporter", "-Dconfig.file=/opt/docker/conf/application.conf", "-Dlogback.configurationFile=/opt/docker/conf/logback.xml"]
    command: ["/opt/docker/bin/kafka-lag-exporter", "-Dconfig.file=/opt/docker/conf/application.conf"]
    ports:
      - "8000:8000"
    volumes:
      - "./kafka-lag-exporter:/opt/docker/conf/"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: zipkin
    environment:
      STORAGE_TYPE: mem
      KAFKA_BOOTSTRAP_SERVERS: kafka-01:19091
    ports:
      - 9411:9411

volumes:
  prometheus-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind" 
      device: "/opt/monitoring/prometheus/data/"
  grafana-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind" 
      device: "/opt/monitoring/grafana/data/"

networks:
  default:
    name: confluent
